#!/usr/bin/env python3
"""
Build the Squarespace injection bundle from the Netlify site.

The Netlify site in ./site is the single source of truth. This script rewrites
it into the four things Squarespace actually accepts:

  1. one site-wide Header Code Injection  (fonts, CSS, favicon, chrome overrides)
  2. one site-wide Footer Code Injection  (the JS)
  3. one Code Block per page              (the markup)
  4. a README with the click path

Squarespace has no way to serve our /assets directory, so every asset URL is
rewritten to an absolute URL on a host that does. By default that is the
Netlify deploy, which means Netlify serves the assets and Squarespace serves
the pages. Pass --base to point somewhere else.

    python build-squarespace.py --base https://velum-corp.netlify.app

Re-run it after every change to ./site.
"""

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).parent
SITE = ROOT / "site"
OUT = ROOT / "squarespace"

# Squarespace page slugs. Left side is the file in ./site, right side is the
# URL slug you give the page in Squarespace.
PAGES = {
    "index.html": ("home", "Inicio / Home"),
    "houses.html": ("houses", "Las casas / Houses"),
    "about.html": ("about", "El grupo / The group"),
    "contact.html": ("contact", "Contacto / Contact"),
}

# Squarespace 7.1 chrome we hide so the Velum design owns the viewport.
# These selectors are template-dependent: if the built-in header still shows,
# inspect the page and add its selector here.
CHROME_OVERRIDES = """
/* ---- Squarespace chrome overrides -------------------------------------- */
/* The Velum pages carry their own masthead and footer, so Squarespace's are
   hidden and its section padding is removed. Selectors are 7.1; if a built-in
   header still appears, inspect the page and add its selector to this list. */
#header,
.header,
#footer-sections,
.sqs-announcement-bar-dropzone { display: none !important; }

#sections .page-section,
.page-section > .content-wrapper {
  padding: 0 !important;
  margin: 0 !important;
  max-width: none !important;
}
.sqs-block { padding: 0 !important; }
.sqs-block-content { padding: 0 !important; }
#siteWrapper, #canvas, .site-wrapper { padding: 0 !important; margin: 0 !important; }

/* Squarespace sets its own body type; the Velum system takes it back. */
body, .sqs-block-html p { font-family: 'Montserrat', system-ui, sans-serif; }
"""


def rewrite(html: str, base: str) -> str:
    """Point every root-relative URL at the asset host, and page links at slugs."""
    # page links first, before the generic /... rule can touch them
    for src, (slug, _) in PAGES.items():
        target = "/" if slug == "home" else "/" + slug
        html = html.replace(f'href="/{src}"', f'href="{target}"')
        html = html.replace(f'href="/{src}#', f'href="{target}#')
    html = html.replace('href="/gracias.html"', 'href="/gracias"')
    html = html.replace('href="/"', 'href="/"')

    # every remaining root-relative asset URL becomes absolute
    html = re.sub(r'(?<=")/(assets/[^"]*)', rf"{base}/\1", html)
    html = re.sub(r'(?<=,\s)/(assets/[^\s,"]*)', rf"{base}/\1", html)
    html = re.sub(r'(?<=srcset=")/(assets/)', rf"{base}/\1", html)
    return html


def extract(html: str, tag: str, cls: str = "") -> str:
    """Pull one top-level element out of the page source."""
    if cls:
        pat = rf"<{tag}[^>]*class=\"{cls}\"[^>]*>.*?</{tag}>"
    else:
        pat = rf"<{tag}[^>]*>.*?</{tag}>"
    m = re.search(pat, html, re.S)
    return m.group(0) if m else ""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--base",
        default="https://velum-corp.netlify.app",
        help="absolute URL of the host serving /assets (no trailing slash)",
    )
    args = ap.parse_args()
    base = args.base.rstrip("/")

    if not SITE.exists():
        print(f"error: {SITE} not found", file=sys.stderr)
        return 1
    OUT.mkdir(exist_ok=True)

    css = (SITE / "assets/css/velum.css").read_text(encoding="utf8")

    # ---- 1. header injection ---------------------------------------------
    header = f"""<!-- ======================================================================
     VELUM ENTERPRISE - Squarespace SITE-WIDE HEADER injection
     Paste into: Settings > Advanced > Code Injection > Header
     Generated by build-squarespace.py. Do not hand-edit; edit site/ and rerun.
     Assets are served from: {base}
     ====================================================================== -->

<link rel="preconnect" href="{base}" crossorigin>
<link rel="preload" as="font" type="font/woff2" href="{base}/assets/fonts/cinzel-latin.woff2" crossorigin>
<link rel="preload" as="font" type="font/woff2" href="{base}/assets/fonts/montserrat-latin.woff2" crossorigin>
<link rel="stylesheet" href="{base}/assets/css/velum.css">

<link rel="icon" href="{base}/assets/logo/icon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="{base}/assets/logo/apple-touch-icon.png">
<meta name="theme-color" content="#0B1D34">

<style>
{CHROME_OVERRIDES}
</style>
"""
    (OUT / "00-site-header-injection.html").write_text(header, encoding="utf8")

    # ---- 2. footer injection ---------------------------------------------
    footer_inj = f"""<!-- ======================================================================
     VELUM ENTERPRISE - Squarespace SITE-WIDE FOOTER injection
     Paste into: Settings > Advanced > Code Injection > Footer
     ====================================================================== -->

<script src="{base}/assets/js/velum.js" defer></script>
"""
    (OUT / "01-site-footer-injection.html").write_text(footer_inj, encoding="utf8")

    # ---- 3. one code block per page --------------------------------------
    built = []
    for src, (slug, label) in PAGES.items():
        raw = (SITE / src).read_text(encoding="utf8")
        head = extract(raw, "header", "masthead")
        main = extract(raw, "main")
        foot = extract(raw, "footer", "foot")

        body = rewrite(head + "\n\n" + main + "\n\n" + foot, base)

        # The Netlify form cannot work on Squarespace. Replace it with a marker.
        if "contact-form" in body:
            body = re.sub(
                r"<form id=\"contact-form\".*?</form>",
                "<!-- FORM: Netlify Forms does not run on Squarespace.\n"
                "     Delete this comment, add a Squarespace Form Block here,\n"
                "     and it will inherit the .field styles from velum.css. -->\n"
                "        <p class=\"muted\">"
                "<a class=\"tlink\" href=\"mailto:support@velumcorp.com\">"
                "support@velumcorp.com</a></p>",
                body,
                flags=re.S,
            )

        out = f"""<!-- ======================================================================
     VELUM ENTERPRISE - Squarespace page: {label}
     Page URL slug: /{'' if slug == 'home' else slug}

     Paste into: the page > add a Code Block > paste all of this.
     Set the Code Block to full width and turn OFF "Display Source".
     ====================================================================== -->

{body}
"""
        name = f"page-{slug}.html"
        (OUT / name).write_text(out, encoding="utf8")
        built.append((name, slug, label, len(out)))

    print(f"asset base: {base}")
    print(f"css:        {len(css) / 1024:.1f} KB (linked, not inlined)")
    for name, slug, label, size in built:
        print(f"  {name:<20} /{slug:<8} {size / 1024:6.1f} KB  {label}")
    print(f"\nwrote {len(built) + 2} files to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
